name: CI

permissions:
  contents: read

on:
  workflow_call:
  pull_request:
    branches: [ main ]

env:
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: short
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  test-msrv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: Install minimal supported Rust version
      uses: dtolnay/rust-toolchain@1.85

    - name: Run cargo test
      run: cargo test --verbose

  test-all-features:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: Install stable Rust version
      uses: dtolnay/rust-toolchain@stable

    - name: Run cargo test
      run: cargo test --verbose --all-features

  clippy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: Run clippy
      run: cargo clippy --all-features -- -D clippy::all

  cargo-fmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: Run cargo fmt
      run: cargo fmt -- --check
